apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-pipeline
  namespace: team-a
spec:
  params:
    - name: IMAGE
      type: string
  tasks:
    - name: build
      taskRef:
        name: build-and-push
      params:
        - name: IMAGE
          value: $(params.IMAGE)
