apiVersion: apps/v1
kind: Deployment
metadata:
  name: liveness-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: liveness-demo
  template:
    metadata:
      labels:
        app: liveness-demo
    spec:
      containers:
        - name: app
          image: busybox
          args:
            - /bin/sh
            - -c
            - |
              touch /tmp/healthy;
              echo "🟢 Liveness demo started";
              while true; do
                if [ -f /tmp/healthy ]; then
                  echo "✅ Healthy";
                else
                  echo "❌ Unhealthy";
                fi;
                sleep 3;
              done
          livenessProbe:
            exec:
              command:
                - cat
                - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 5
